server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
#      label: master
      server:
        git:
          uri: https://github.com/pengchong0308/springcloud-config.git #GitHub上面的git仓库名字
#          search-paths: spring-cloud-config

#          测试路径：http://config-3344.com:3344/springCloudConfig/dev/master
#                    http://config-3344.com:3344/application/dev/master
# spring.cloud.config.server.git.uri：配置git仓库地址
# spring.cloud.config.server.git.searchPaths：配置仓库路径
# spring.cloud.config.label：配置仓库的分支
# spring.cloud.config.server.git.username：访问git仓库的用户名
# spring.cloud.config.server.git.password：访问git仓库的用户密码

